<?php

return [
    'params' => [
        /**
         * menu для разных ролей 
         */
        'menuItems' => [
            ['label' => 'Ежедневник', 'url' => '/old_app/raspis_show.php', 'roles' => ['admin', 'therapist', 'orthopedist', 'surgeon', 'orthodontist',]],
            ['label' => 'Соcтавление пакета расписаний', 'url' => '/old_app/raspis_newpack.php', 'roles' => ['admin',]],
            ['label' => 'Изменить расписание', 'url' => '/old_app/raspis_change.php', 'roles' => ['admin',]],
            ['label' => 'Назначение пациентов', 'url' => '/old_app/naznach_pat.php', 'roles' => ['admin', 'therapist', 'orthopedist', 'surgeon', 'orthodontist', 'recorder',]],
            ['label' => 'Пациенты на сегодня регитратура', 'url' => '/old_app/pat_tooday_reg.php', 'roles' => ['recorder',]],
            ['label' => 'Пациенты на сегодня ортодонтия', 'url' => '/old_app/pat_tooday_orto.php', 'roles' => ['orthodontist',]],
            ['label' => 'Пациенты на сегодня врачи', 'url' => '/old_app/pat_tooday.php', 'roles' => ['therapist', 'orthopedist', 'surgeon',]],
            ['label' => 'График работы персонала', 'url' => '/old_app/sotr_time.php', 'roles' => ['recorder',]],
            ['label' => 'Табель', 'url' => '/old_app/tabel.php', 'roles' => ['admin', 'senior nurse',]],
            //['label' => 'Добавить нового', 'url' => '/old_app/PatWork.php?add=add', 'roles' => ['admin', 'therapist', 'orthopedist', 'surgeon', 'orthodontist', 'recorder', 'senior nurse',]],
           // ['label' => 'Работа с пациентами', 'url' => '/old_app/pat.php', 'roles' => ['admin', 'therapist', 'orthopedist', 'surgeon', 'orthodontist', 'recorder', 'senior nurse',]],
            ['label' => 'Диспансеризация', 'url' => '/old_app/disp.php', 'roles' => ['recorder',]],
            ['label' => 'День рождения пациентов', 'url' => '/old_app/dr_pat.php', 'roles' => ['recorder',]],
            ['label' => 'Работа с пациентами ортодонтия', 'url' => '/old_app/pat_card_orto.php', 'roles' => ['admin', 'orthodontist', 'recorder',]],
            ['label' => 'Выданные карты', 'url' => '/old_app/discount.php?act=view', 'roles' => ['admin', 'recorder',]],
            ['label' => 'Новые карты', 'url' => '/old_app/discount.php?act=new', 'roles' => ['admin',]],
            ['label' => 'Выдача карт', 'url' => '/old_app/discount.php?act=make', 'roles' => ['admin', 'recorder',]],
            ['label' => 'Виды карт', 'url' => '/old_app/discount.php?act=types', 'roles' => ['admin',]],
            ['label' => 'Отчёт за день (чеки)', 'url' => '/old_app/doc_den_ch.php', 'roles' => ['therapist', 'orthopedist', 'surgeon', 'orthodontist',]],
            ['label' => 'Отчёт за период (чеки)', 'url' => '/old_app/doc_den_ch_per.php', 'roles' => ['therapist', 'orthopedist', 'surgeon', 'orthodontist',]],
            ['label' => 'Отчёт за день (оплаты)', 'url' => '/old_app/doc_den_opl.php', 'roles' => ['therapist', 'orthopedist', 'surgeon', 'orthodontist',]],
            ['label' => 'Отчёт за период (оплаты)', 'url' => '/old_app/doc_den_opl_per.php', 'roles' => ['therapist', 'orthopedist', 'surgeon', 'orthodontist',]],
            ['label' => 'Должники', 'url' => '/old_app/dolzh.php', 'roles' => ['therapist', 'orthopedist', 'surgeon', 'orthodontist',]],
            ['label' => 'Отчёт за месяц', 'url' => '/old_app/month_otch.php', 'roles' => ['therapist', 'orthopedist', 'surgeon', 'orthodontist',]],
            ['label' => 'Все пациенты', 'url' => '/old_app/doc_den_ch_per2.php', 'roles' => ['therapist', 'orthopedist', 'surgeon', 'orthodontist',]],
            ['label' => 'Диспансеризация врачи', 'url' => '/old_app/disp_vrach.php', 'roles' => ['therapist', 'orthopedist', 'surgeon', 'orthodontist',]],
            //['label' => 'Сотрудники', 'url' => '/old_app/spr_sotr.php', 'roles' => ['admin', 'senior nurse',]],
            ['label' => 'Реквизиты фирм', 'url' => '/old_app/spr_firm.php', 'roles' => ['admin',]],
            ['label' => 'Договора', 'url' => '/old_app/spr_dogovora.php', 'roles' => ['admin',]],
            ['label' => 'Клише', 'url' => '/old_app/klishe.php', 'roles' => ['admin',]],
            ['label' => 'Диагноз', 'url' => '/old_app/spr_ds.php', 'roles' => ['admin',]],
            ['label' => 'Манипуляции', 'url' => '/old_app/spr_manip.php', 'roles' => ['admin',]],
            ['label' => 'Прейскуранты', 'url' => '/old_app/spr_preysk.php', 'roles' => ['admin',]],
            ['label' => 'Жалобы', 'url' => '/old_app/spr_zh.php', 'roles' => ['admin',]],
            ['label' => 'Анамнез', 'url' => '/old_app/spr_an.php', 'roles' => ['admin',]],
            ['label' => 'Объективно', 'url' => '/old_app/spr_ob.php', 'roles' => ['admin',]],
            ['label' => 'Должности', 'url' => '/old_app/spr_dolzh.php', 'roles' => ['admin',]],
            ['label' => 'Приём оплаты', 'url' => '/old_app/pr_opl.php', 'roles' => ['recorder',]],
            ['label' => 'Долги', 'url' => '/old_app/pr_dolg.php', 'roles' => ['recorder',]],
            ['label' => 'Приём аванса', 'url' => '/old_app/pr_avans.php', 'roles' => ['recorder',]],
            ['label' => 'Выдача денег', 'url' => '/old_app/vid_deneg.php?step=1', 'roles' => ['recorder',]],
            ['label' => 'Начало смены', 'url' => '/old_app/kassa.php?action=nach&step=1', 'roles' => ['recorder',]],
            ['label' => 'Окончание смены', 'url' => '/old_app/kassa.php?action=okonch&step=1', 'roles' => ['recorder',]],
            ['label' => 'Приём оплаты ортодонтия', 'url' => '/old_app/pr_opl_orto.php', 'roles' => ['recorder',]],
            ['label' => 'Должники ортодонтия', 'url' => '/old_app/pr_dolg_orto.php', 'roles' => ['recorder',]],
            ['label' => 'Продажа гигиены', 'url' => '/old_app/pr_opl_hyg.php', 'roles' => ['recorder',]],
            ['label' => 'Подарочные сертификаты', 'url' => '/old_app/certif_gift.php?action=add&step=1', 'roles' => ['recorder',]],
            ['label' => 'Выданные сертификаты', 'url' => '/old_app/certif_gift.php', 'roles' => ['recorder',]],
            ['label' => 'Финансовый отчёт за день', 'url' => '/old_app/reg_den_opl.php', 'roles' => ['recorder',]],
            ['label' => 'Установить финансовый период', 'url' => '/old_app/fin_per.php', 'roles' => ['accountant',]],
            ['label' => 'Заработная плата', 'url' => '/old_app/accountant_zp.php', 'roles' => ['accountant',]],
            ['label' => 'Зарплатная карта', 'url' => '/old_app/accountant_zc.php', 'roles' => ['accountant',]],
            ['label' => 'Табель', 'url' => '/old_app/sotr_time.php', 'roles' => ['accountant', 'director',]],
            ['label' => 'Каталог материалов', 'url' => '/old_app/mater.php', 'roles' => ['senior nurse',]],
            ['label' => 'Остаток материалов', 'url' => '/old_app/mater_ost.php', 'roles' => ['senior nurse',]],
            ['label' => 'Приход материала', 'url' => '/old_app/mater_prih.php', 'roles' => ['senior nurse',]],
            ['label' => 'Выдача материалов', 'url' => '/old_app/mater_vid.php', 'roles' => ['senior nurse',]],
            ['label' => 'Учёт приборов', 'url' => '/old_app/tech_sp.php', 'roles' => ['senior nurse',]],
            ['label' => 'Учёт расхода материалов', 'url' => '/old_app/mater_uch.php', 'roles' => ['senior nurse',]],
            ['label' => 'Еденицы измерения', 'url' => '/old_app/spr_edizm.php', 'roles' => ['senior nurse',]],
            ['label' => 'Mеста хренния материалов', 'url' => '/old_app/mater_mesta_hr.php', 'roles' => ['senior nurse',]],
            ['label' => 'Составление заявки', 'url' => '/old_app/mater_order.php', 'roles' => ['senior nurse',]],
            ['label' => 'Списание материалов', 'url' => '/old_app/mater_spis.php', 'roles' => ['senior nurse',]],
            ['label' => 'Установка соотвествий для автосписания', 'url' => '/old_app/mater_sootv.php', 'roles' => ['senior nurse',]],
            ['label' => 'Отчёт по автосписанию', 'url' => '/old_app/mater_sootv_otch.php', 'roles' => ['senior nurse',]],
            ['label' => 'Отчёты по приходам', 'url' => '/old_app/mater_otch_prih.php', 'roles' => ['senior nurse',]],
            ['label' => 'Отчёты по выдаче', 'url' => '/old_app/mater_otch_vid.php', 'roles' => ['senior nurse',]],
            ['label' => 'отчёты по списанию', 'url' => '/old_app/mater_otch_spis.php', 'roles' => ['senior nurse',]],
            ['label' => 'Финансовый отчёт за день директор', 'url' => '/old_app/dir_den_opl.php', 'roles' => ['director',]],
            ['label' => 'Финансовый отчёт по врачам за период', 'url' => '/old_app/dir_den_opl_per.php', 'roles' => ['director',]],
            ['label' => 'Финансовый отчёт по клинике за период', 'url' => '/old_app/dir_den_opl_per_clin.php', 'roles' => ['director',]],
            ['label' => 'Отчёт по договорам', 'url' => '/old_app/dir_dog.php', 'roles' => ['director',]],
            ['label' => 'Учёт снимков', 'url' => '/old_app/rentgen.php?type=today', 'roles' => ['radiologist',]],
            ['label' => 'Отчёты', 'url' => '/old_app/doc_den_opl_radiologist_per.php', 'roles' => ['radiologist',]],
            ['label' => 'Табель', 'url' => '/old_app/sotr_time.php', 'roles' => ['radiologist',]],
        ],
    ],
];
