<?php

return [
    'params' => [
        /**
         * menu для разных ролей 
         */
        'menuItems' => [
            'admin' => [
                ['label' => 'Ежедневник', 'url' => '/old_app/raspis_show.php',],
                ['label' => 'Соcтавление пакета расписаний', 'url' => '/old_app/raspis_newpack.php',],
                ['label' => 'Изменить расписание', 'url' => '/old_app/raspis_change.php',],
                ['label' => 'Назначение пациентов', 'url' => '/old_app/naznach_pat.php',],
                ['label' => 'Табель', 'url' => '/old_app/tabel.php',],
                ['label' => 'Добавить нового', 'url' => '/old_app/PatWork.php?add=add',],
                ['label' => 'Работа с пациентами', 'url' => '/old_app/pat.php',],
                ['label' => 'Работа с пациентами ортодонтия', 'url' => '/old_app/pat_card_orto.php',],
                ['label' => 'Выданные карты', 'url' => '/old_app/discount.php?act=view',],
                ['label' => 'Новые карты', 'url' => '/old_app/discount.php?act=new',],
                ['label' => 'Выдача карт', 'url' => '/old_app/discount.php?act=make',],
                ['label' => 'Виды карт', 'url' => '/old_app/discount.php?act=types',],
                ['label' => 'Сотрудники', 'url' => '/old_app/spr_sotr.php',],
                ['label' => 'Пользователи', 'url' => '/old_app/spr_polz.php',],
                ['label' => 'Права пользователей', 'url' => '/old_app/prpolz.php',],
                ['label' => 'Реквизиты фирм', 'url' => '/old_app/spr_firm.php',],
                ['label' => 'Договора', 'url' => '/old_app/spr_dogovora.php',],
                ['label' => 'Клише', 'url' => '/old_app/klishe.php',],
                ['label' => 'Диагноз', 'url' => '/old_app/spr_ds.php',],
                ['label' => 'Манипуляции', 'url' => '/old_app/spr_manip.php',],
                ['label' => 'Прейскуранты', 'url' => '/old_app/spr_preysk.php',],
                ['label' => 'Жалобы', 'url' => '/old_app/spr_zh.php',],
                ['label' => 'Анамнез', 'url' => '/old_app/spr_an.php',],
                ['label' => 'Объективно', 'url' => '/old_app/spr_ob.php',],
                ['label' => 'Должности', 'url' => '/old_app/spr_dolzh.php',],
            ],
            'therapist' => [
                ['label' => 'Ежедневник', 'url' => '/old_app/raspis_doctor_show.php',],
                ['label' => 'Назначение пациентов', 'url' => '/old_app/naznach_pat.php',],
                ['label' => 'Пациенты на сегодня врачи', 'url' => '/old_app/pat_tooday.php',],
                ['label' => 'Добавить нового', 'url' => '/old_app/PatWork.php?add=add',],
                ['label' => 'Работа с пациентами', 'url' => '/old_app/pat.php',],
                ['label' => 'Отчёт за день (чеки)', 'url' => '/old_app/doc_den_ch.php',],
                ['label' => 'Отчёт за период (чеки)', 'url' => '/old_app/doc_den_ch_per.php',],
                ['label' => 'Отчёт за день (оплаты)', 'url' => '/old_app/doc_den_opl.php',],
                ['label' => 'Отчёт за период (оплаты)', 'url' => '/old_app/doc_den_opl_per.php',],
                ['label' => 'Должники', 'url' => '/old_app/dolzh.php',],
                ['label' => 'Отчёт за месяц', 'url' => '/old_app/month_otch.php',],
                ['label' => 'Все пациенты', 'url' => '/old_app/doc_den_ch_per2.php',],
                ['label' => 'Диспансеризация врачи', 'url' => '/old_app/disp_vrach.php',],
            ],
            'orthopedist' => [
                ['label' => 'Ежедневник', 'url' => '/old_app/raspis_doctor_show.php',],
                ['label' => 'Назначение пациентов', 'url' => '/old_app/naznach_pat.php',],
                ['label' => 'Пациенты на сегодня врачи', 'url' => '/old_app/pat_tooday.php',],
                ['label' => 'Добавить нового', 'url' => '/old_app/PatWork.php?add=add',],
                ['label' => 'Работа с пациентами', 'url' => '/old_app/pat.php',],
                ['label' => 'Отчёт за день (чеки)', 'url' => '/old_app/doc_den_ch.php',],
                ['label' => 'Отчёт за период (чеки)', 'url' => '/old_app/doc_den_ch_per.php',],
                ['label' => 'Отчёт за день (оплаты)', 'url' => '/old_app/doc_den_opl.php',],
                ['label' => 'Отчёт за период (оплаты)', 'url' => '/old_app/doc_den_opl_per.php',],
                ['label' => 'Должники', 'url' => '/old_app/dolzh.php',],
                ['label' => 'Отчёт за месяц', 'url' => '/old_app/month_otch.php',],
                ['label' => 'Все пациенты', 'url' => '/old_app/doc_den_ch_per2.php',],
                ['label' => 'Диспансеризация врачи', 'url' => '/old_app/disp_vrach.php',],
            ],
            'surgeon' => [
                ['label' => 'Ежедневник', 'url' => '/old_app/raspis_doctor_show.php',],
                ['label' => 'Назначение пациентов', 'url' => '/old_app/naznach_pat.php',],
                ['label' => 'Пациенты на сегодня врачи', 'url' => '/old_app/pat_tooday.php',],
                ['label' => 'Добавить нового', 'url' => '/old_app/PatWork.php?add=add',],
                ['label' => 'Работа с пациентами', 'url' => '/old_app/pat.php',],
                ['label' => 'Отчёт за день (чеки)', 'url' => '/old_app/doc_den_ch.php',],
                ['label' => 'Отчёт за период (чеки)', 'url' => '/old_app/doc_den_ch_per.php',],
                ['label' => 'Отчёт за день (оплаты)', 'url' => '/old_app/doc_den_opl.php',],
                ['label' => 'Отчёт за период (оплаты)', 'url' => '/old_app/doc_den_opl_per.php',],
                ['label' => 'Должники', 'url' => '/old_app/dolzh.php',],
                ['label' => 'Отчёт за месяц', 'url' => '/old_app/month_otch.php',],
                ['label' => 'Все пациенты', 'url' => '/old_app/doc_den_ch_per2.php',],
                ['label' => 'Диспансеризация врачи', 'url' => '/old_app/disp_vrach.php',],
            ],
            'orthodontist' => [
                ['label' => 'Ежедневник', 'url' => '/old_app/raspis_doctor_show.php',],
                ['label' => 'Назначение пациентов', 'url' => '/old_app/naznach_pat.php',],
                ['label' => 'Пациенты на сегодня ортодонтия', 'url' => '/old_app/pat_tooday_orto.php',],
                ['label' => 'Добавить нового', 'url' => '/old_app/PatWork.php?add=add',],
                ['label' => 'Работа с пациентами', 'url' => '/old_app/pat.php',],
                ['label' => 'Работа с пациентами ортодонтия', 'url' => '/old_app/pat_card_orto.php',],
                ['label' => 'Отчёт за день (чеки)', 'url' => '/old_app/doc_den_ch.php',],
                ['label' => 'Отчёт за период (чеки)', 'url' => '/old_app/doc_den_ch_per.php',],
                ['label' => 'Отчёт за день (оплаты)', 'url' => '/old_app/doc_den_opl.php',],
                ['label' => 'Отчёт за период (оплаты)', 'url' => '/old_app/doc_den_opl_per.php',],
                ['label' => 'Должники', 'url' => '/old_app/dolzh.php',],
                ['label' => 'Отчёт за месяц', 'url' => '/old_app/month_otch.php',],
                ['label' => 'Все пациенты', 'url' => '/old_app/doc_den_ch_per2.php',],
                ['label' => 'Диспансеризация врачи', 'url' => '/old_app/disp_vrach.php',],
            ],
            'recorder' => [
                ['label' => 'Назначение пациентов', 'url' => '/old_app/naznach_pat.php',],
                ['label' => 'Пациенты на сегодня регитратура', 'url' => '/old_app/pat_tooday_reg.php',],
                ['label' => 'График работы персонала', 'url' => '/old_app/sotr_time.php',],
                ['label' => 'Добавить нового', 'url' => '/old_app/PatWork.php?add=add',],
                ['label' => 'Работа с пациентами', 'url' => '/old_app/pat.php',],
                ['label' => 'Диспансеризация', 'url' => '/old_app/disp.php',],
                ['label' => 'День рождения пациентов', 'url' => '/old_app/dr_pat.php',],
                ['label' => 'Работа с пациентами ортодонтия', 'url' => '/old_app/pat_card_orto.php',],
                ['label' => 'Выданные карты', 'url' => '/old_app/discount.php?act=view',],
                ['label' => 'Выдача карт', 'url' => '/old_app/discount.php?act=make',],
                ['label' => 'Приём оплаты', 'url' => '/old_app/pr_opl.php',],
                ['label' => 'Долги', 'url' => '/old_app/pr_dolg.php',],
                ['label' => 'Приём аванса', 'url' => '/old_app/pr_avans.php',],
                ['label' => 'Выдача денег', 'url' => '/old_app/vid_deneg.php?step=1',],
                ['label' => 'Начало смены', 'url' => '/old_app/kassa.php?action=nach&step=1',],
                ['label' => 'Окончание смены', 'url' => '/old_app/kassa.php?action=okonch&step=1',],
                ['label' => 'Приём оплаты ортодонтия', 'url' => '/old_app/pr_opl_orto.php',],
                ['label' => 'Должники ортодонтия', 'url' => '/old_app/pr_dolg_orto.php',],
                ['label' => 'Продажа гигиены', 'url' => '/old_app/pr_opl_hyg.php',],
                ['label' => 'Подарочные сертификаты', 'url' => '/old_app/certif_gift.php?action=add&step=1',],
                ['label' => 'Выданные сертификаты', 'url' => '/old_app/certif_gift.php',],
                ['label' => 'Финансовый отчёт за день', 'url' => '/old_app/reg_den_opl.php',],
            ],
            'accountant' => [
                ['label' => 'Установить финансовый период', 'url' => '/old_app/fin_per.php',],
                ['label' => 'Заработная плата', 'url' => '/old_app/buhg_zp.php',],
                ['label' => 'Зарплатная карта', 'url' => '/old_app/buhg_zc.php',],
                ['label' => 'Табель', 'url' => '/old_app/sotr_time.php',],
            ],
            'senior nurse' => [
                ['label' => 'Табель', 'url' => '/old_app/tabel.php',],
                ['label' => 'Добавить нового', 'url' => '/old_app/PatWork.php?add=add',],
                ['label' => 'Работа с пациентами', 'url' => '/old_app/pat.php',],
                ['label' => 'Сотрудники', 'url' => '/old_app/spr_sotr.php',],
                ['label' => 'Каталог материалов', 'url' => '/old_app/mater.php',],
                ['label' => 'Остаток материалов', 'url' => '/old_app/mater_ost.php',],
                ['label' => 'Приход материала', 'url' => '/old_app/mater_prih.php',],
                ['label' => 'Выдача материалов', 'url' => '/old_app/mater_vid.php',],
                ['label' => 'Учёт приборов', 'url' => '/old_app/tech_sp.php',],
                ['label' => 'Учёт расхода материалов', 'url' => '/old_app/mater_uch.php',],
                ['label' => 'Еденицы измерения', 'url' => '/old_app/spr_edizm.php',],
                ['label' => 'Mеста хренния материалов', 'url' => '/old_app/mater_mesta_hr.php',],
                ['label' => 'Составление заявки', 'url' => '/old_app/mater_order.php',],
                ['label' => 'Списание материалов', 'url' => '/old_app/mater_spis.php',],
                ['label' => 'Установка соотвествий для автосписания', 'url' => '/old_app/mater_sootv.php',],
                ['label' => 'Отчёт по автосписанию', 'url' => '/old_app/mater_sootv_otch.php',],
                ['label' => 'Отчёты по приходам', 'url' => '/old_app/mater_otch_prih.php',],
                ['label' => 'Отчёты по выдаче', 'url' => '/old_app/mater_otch_vid.php',],
                ['label' => 'отчёты по списанию', 'url' => '/old_app/mater_otch_spis.php',],
            ],
            'director' => [
                ['label' => 'Табель', 'url' => '/old_app/sotr_time.php',],
                ['label' => 'Финансовый отчёт за день директор', 'url' => '/old_app/dir_den_opl.php',],
                ['label' => 'Финансовый отчёт по врачам за период', 'url' => '/old_app/dir_den_opl_per.php',],
                ['label' => 'Финансовый отчёт по клинике за период', 'url' => '/old_app/dir_den_opl_per_clin.php',],
                ['label' => 'Отчёт по договорам', 'url' => '/old_app/dir_dog.php',],
            ],
            'radiologist' => [
                ['label' => 'Учёт снимков', 'url' => '/old_app/rentgen.php?type=today',],
                ['label' => 'Отчёты', 'url' => '/old_app/doc_den_opl_xray_per.php',],
                ['label' => 'Табель', 'url' => '/old_app/sotr_time.php',],
            ],
        ],
    ],
];
