<?php

namespace common\modules\statistics\controllers;

use common\modules\reports\models\FinancialPeriods;
use common\modules\statistics\models\DoctorStatistics;
use common\modules\userInterface\models\UserInterface;
use Yii;

/**
 * Метрики:     |Пациенты       |Финансы            |Манипулфции|
 *              |-----------    |-----------        |-----------|
 *              |Первичные      |Отработано Часов   |
 *              |Реферативн     |Выручка
 *              |               |Выричка в час
 */
class DoctorsController extends \yii\web\Controller

{
    public function beforeAction($action)
    {
//        // TODO: Change the autogenerated stub
//        $oldDb = Yii::$app->db;
//        $db = Yii::$app->set('db', Yii::$app->second_db);
        //$post->save();
        //  Yii::$app->set('db', $oldDb);
        return parent::beforeAction($action);
    }

    private function getFinancialPeriod()
    {
        if (Yii::$app->request->get('financialPeriodId') and FinancialPeriods::findOne(Yii::$app->request->get('financialPeriodId')) != null) {
            $financialPeriod = FinancialPeriods::findOne(Yii::$app->request->get('financialPeriodId'));
        } else {
            $financialPeriod = FinancialPeriods::getPeriodForCurrentDate();
        }
        return $financialPeriod;
    }

    public function actionIndex($financialPeriodId = null)
    {

        $doctorStatistics = DoctorStatistics::getForFinancialPeriod($this->getFinancialPeriod());
        return $this->render('index', [
            'doctorStatistics' => $doctorStatistics
        ]);

    }

    public function actionDaily()
    {
        $financialPeriod = $this->getFinancialPeriod();

        $doctorStatistics = DoctorStatistics::getDaily(UserInterface::getFormatedDate($financialPeriod->nach));
        return $this->render('index', [
            'doctorStatistics' => $doctorStatistics
        ]);

    }

}
