<?php

namespace common\modules\statistics\controllers;

use common\modules\reports\models\FinancialPeriods;
use common\modules\statistics\models\ClinicStatistic;
use common\modules\statistics\models\DoctorStatistics;
use common\modules\statistics\models\HygieneProducts;
use common\modules\statistics\models\Material;
use common\modules\statistics\models\StatisticsCount;
use common\modules\statistics\models\XRayCount;
use common\modules\userInterface\models\UserInterface;
use Yii;

class RevenueController extends \yii\web\Controller
{
    public function beforeAction($action)
    {
//        // TODO: Change the autogenerated stub
//        $oldDb = Yii::$app->db;
        //$db = Yii::$app->set('db', Yii::$app->second_db);
        //$post->save();
        //  Yii::$app->set('db', $oldDb);
        return parent::beforeAction($action);
    }

    private function getFinancialPeriod()
    {
        if (Yii::$app->request->get('financialPeriodId') and FinancialPeriods::findOne(Yii::$app->request->get('financialPeriodId')) != null) {
            $financialPeriod = FinancialPeriods::findOne(Yii::$app->request->get('financialPeriodId'));
        } else {
            $financialPeriod = FinancialPeriods::getPeriodForCurrentDate();
        }
        return $financialPeriod;
    }

    public function actionIndex($financialPeriodId = null)
    {
//        if (!$financialPeriodId){
//            $hygieneProductsStatistics=HygieneProducts::getForFinancialPeriod(FinancialPeriods::getPeriodForCurrentDate());
//        }
//        else{
//            $hygieneProductsStatistics=HygieneProducts::getForFinancialPeriod(FinancialPeriods::findOne($financialPeriodId));
//        }
        $hygieneProductsStatistics = [];
        $material =[];
        $xRayStatistic = [];
        $clinicStatistic = [];
        $periods=StatisticsCount::getPeriods();

        foreach ($periods as $period){
            $hygieneProductsStatistics [$period['id']]= HygieneProducts::getForPeriod($period['startDate'],$period['endDate']);
            $material [$period['id']]= Material::getForPeriod($period['startDate'],$period['endDate']);
            $xRayStatistic [$period['id']]= XRayCount::getForPeriod($period['startDate'],$period['endDate']);
            $clinicStatistic [$period['id']]= ClinicStatistic::getForPeriod($period['startDate'],$period['endDate']);
        }
        $doctorStatistics=DoctorStatistics::getForFinancialPeriod($this->getFinancialPeriod());

        return $this->render('index', [
            'hygieneProductsStatistics' => $hygieneProductsStatistics,
            'material' => $material,
            'clinicStatistic' => $clinicStatistic,
            'xRayStatistic' => $xRayStatistic,
            'doctorStatistics'=>$doctorStatistics,
            'periods' => $periods,
        ]);
    }

    public function actionHygieneProduct($financialPeriodId = null)
    {
        $hygieneProductsStatistics = HygieneProducts::getForFinancialPeriod($this->getFinancialPeriod());
        return $this->render('hygiene-product', [
            'hygieneProductsStatistics' => $hygieneProductsStatistics,
        ]);
    }

    public function actionMaterial($financialPeriodId = null)
    {
        $material = Material::getForFinancialPeriod($this->getFinancialPeriod());
        return $this->render('material', [
            'material' => $material,
        ]);
    }

    public function actionClinicStatistic($type)
    {
        if (Yii::$app->request->get('year')){
            $clinicStatistic = ClinicStatistic::getForYear(Yii::$app->request->get('year'));
        }
            else {
                $clinicStatistic = ClinicStatistic::getForFinancialPeriod($this->getFinancialPeriod());
            }


        return $this->render('clinic-statistic', [
            'clinicStatistic' => $clinicStatistic,
            'type' => $type,
        ]);
    }

    public function actionXlsSave($coefficient = false)
    {
        return $this->redirect('/' . StatisticsCount::getXlsxRevenue(StatisticsCount::getPeriods(),$this->getFinancialPeriod()));
    }
}
