<?php


namespace common\modules\invoice\models;


use common\modules\employee\models\Employee;

/**
 * @property Invoice $invoice
 */
class TechnicalOrder extends \common\models\TechnicalOrder
{


    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'invoice_id' => 'Счёт',
            'employee_id' => 'Зубной техник',
            'delivery_date' => 'Дата сдачи работы',
            'technical_order_invoice_id' => 'Заказ-наряд',
            'completed' => 'Сдан',
        ];
    }

    public function getPatientFullName()
    {
        return $this->invoice->patientFullName;
    }

    public function isPaid()
    {
        return $this->invoice->amount_residual == 0;
    }

    public function getTechnic()
    {
        return $this->hasOne(Employee::className(), ['id' => 'employee_id']);
    }
    public function getTechnicFullName()
    {
        return $this->technic->fullName;
    }
    public function getTechnicalOrderInvoice()
    {
        return parent::getTechnicalOrderInvoice(); // TODO: Change the autogenerated stub
//        return $this->hasMany(Invoice::className(),['id' => 'technical_order_invoice_id']);
    }
    public function getInvoice()
    {
        return parent::getInvoice(); // TODO: Change the autogenerated stub
    }
}